#include "configstore.h"

#include <QDBusConnection>
#include <QDBusInterface>
#include <QDBusPendingCall>
#include <QDBusPendingReply>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QSettings>
#include <QStandardPaths>
#include <QTextStream>

namespace {
QString normalizeValue(const QString &raw)
{
    QString value = raw.trimmed();
    if (value.size() >= 2 && value.startsWith('\'') && value.endsWith('\'')) {
        value = value.mid(1, value.length() - 2);
    }
    return value;
}

QString autostartCommand()
{
    const QString appImagePath = qEnvironmentVariable("APPIMAGE");
    return appImagePath.isEmpty() ? QStringLiteral("opencouch") : appImagePath;
}

QString desktopEntryArgument(const QString &argument)
{
    QString escaped = argument;
    escaped.replace(QStringLiteral("\\"), QStringLiteral("\\\\"));
    escaped.replace(QLatin1Char('"'), QStringLiteral("\\\""));
    escaped.replace(QLatin1Char('`'), QStringLiteral("\\`"));
    escaped.replace(QLatin1Char('$'), QStringLiteral("\\$"));
    return QStringLiteral("\"") + escaped + QStringLiteral("\"");
}

QString autostartEntryPath()
{
    return QStandardPaths::writableLocation(QStandardPaths::ConfigLocation)
        + QStringLiteral("/autostart/io.github.gustavobelo.opencouch.desktop");
}

bool updateAutostartEntry(bool enabled)
{
    const QString path = autostartEntryPath();
    QFile entry(path);
    if (!enabled) {
        if (!entry.exists()) {
            return true;
        }
        if (!entry.open(QIODevice::ReadOnly | QIODevice::Text)) {
            return false;
        }
        const bool managedByOpenCouch = QTextStream(&entry).readAll()
            .contains(QStringLiteral("X-Open-Couch-Autostart=true"));
        entry.close();
        return !managedByOpenCouch || entry.remove();
    }

    if (!QDir().mkpath(QFileInfo(path).absolutePath())) {
        return false;
    }
    if (!entry.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
        return false;
    }

    QTextStream stream(&entry);
    stream << "[Desktop Entry]\n"
           << "Type=Application\n"
           << "Name=Open Couch\n"
           << "Exec=" << desktopEntryArgument(autostartCommand()) << "\n"
           << "Icon=io.github.gustavobelo.opencouch\n"
           << "Terminal=false\n"
           << "X-GNOME-Autostart-enabled=true\n"
           << "X-Open-Couch-Autostart=true\n";
    return stream.status() == QTextStream::Ok;
}

bool runningInFlatpak()
{
    return QFileInfo::exists(QStringLiteral("/.flatpak-info"));
}

bool runningInAppImage()
{
    return !qEnvironmentVariable("APPIMAGE").isEmpty();
}
}

ConfigStore::ConfigStore(QObject *parent)
    : QObject(parent)
{
}

QString ConfigStore::configFilePath()
{
    const QString base = qEnvironmentVariableIsSet("XDG_CONFIG_HOME")
        ? qEnvironmentVariable("XDG_CONFIG_HOME")
        : QDir::homePath() + QStringLiteral("/.config");
    return base + QStringLiteral("/open-couch-engine/config.env");
}


QVariantMap ConfigStore::loadConfig() const
{
    QVariantMap config;
    QFile file(configFilePath());
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return config;
    }

    QTextStream stream(&file);
    while (!stream.atEnd()) {
        const QString line = stream.readLine().trimmed();
        if (line.isEmpty() || line.startsWith('#')) {
            continue;
        }

        const int eq = line.indexOf('=');
        if (eq <= 0) {
            continue;
        }

        const QString key = line.left(eq).trimmed();
        QString value = normalizeValue(line.mid(eq + 1));
        if (!key.isEmpty()) {
            config.insert(key, value);
        }
    }
    return config;
}

bool ConfigStore::saveConfig(const QVariantMap &config) const
{
    const QString path = configFilePath();
    QDir().mkpath(QFileInfo(path).absolutePath());

    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
        return false;
    }

    QTextStream stream(&file);
    stream << "# Generated by the Open Couch app - do not edit manually while the app is running\n";
    for (auto it = config.constBegin(); it != config.constEnd(); ++it) {
        stream << it.key() << "='" << it.value().toString().replace("'", "'\\''") << "'\n";
    }
    return true;
}

bool ConfigStore::autostartEnabled() const
{
    return QSettings().value(QStringLiteral("autostartEnabled"), false).toBool();
}

bool ConfigStore::setAutostart(bool enabled) const
{
    if (runningInAppImage()) {
        const bool success = updateAutostartEntry(enabled);
        if (success) {
            QSettings().setValue(QStringLiteral("autostartEnabled"), enabled);
        }
        return success;
    }

    bool success = requestBackgroundPortal(enabled);
    if (!success && !runningInFlatpak()) {
        success = updateAutostartEntry(enabled);
    } else if (success && !enabled) {
        updateAutostartEntry(false);
    }

    if (success) {
        QSettings().setValue(QStringLiteral("autostartEnabled"), enabled);
    }
    return success;
}

bool ConfigStore::requestBackgroundPortal(bool enabled) const
{
    QDBusInterface portal (
        QStringLiteral("org.freedesktop.portal.Desktop"),
        QStringLiteral("/org/freedesktop/portal/desktop"),
        QStringLiteral("org.freedesktop.portal.Background"),
        QDBusConnection::sessionBus()
    );

    if (!portal.isValid()) {
        return false;
    }

    QVariantMap options;
    options[QStringLiteral("reason")] =
        QStringLiteral("Used to monitor Steam and automatically switch displays.");
    options[QStringLiteral("autostart")] = enabled;
    options[QStringLiteral("commandline")] = QStringList{autostartCommand()};
    options[QStringLiteral("dbus-activatable")] = false;

    QDBusPendingCall pending = portal.asyncCall(
        QStringLiteral("RequestBackground"),
        QStringLiteral(""),
        options
    );

    QDBusPendingReply<QDBusObjectPath> reply(pending);
    reply.waitForFinished();
    return !reply.isError();
}

bool ConfigStore::backgroundOnClose() const
{
    return QSettings().value(QStringLiteral("backgroundOnClose"), true).toBool();
}

bool ConfigStore::setBackgroundOnClose(bool enabled) const
{
    QSettings settings;
    settings.setValue(QStringLiteral("backgroundOnClose"), enabled);
    return true;
}

bool ConfigStore::onboardingSeen() const
{
    QSettings settings;
    return settings.value(QStringLiteral("onboardingSeen"), false).toBool();
}

void ConfigStore::setOnboardingSeen(bool seen) const
{
    QSettings settings;
    settings.setValue(QStringLiteral("onboardingSeen"), seen);
}

bool ConfigStore::closeAppsEnabled() const
{
    return loadConfig().value(QStringLiteral("CLOSE_APPS_ENABLED")).toString() == QLatin1String("true");
}

bool ConfigStore::setCloseAppsEnabled(bool enabled) const
{
    QVariantMap config = loadConfig();
    config.insert(QStringLiteral("CLOSE_APPS_ENABLED"), enabled ? QStringLiteral("true") : QStringLiteral("false"));
    return saveConfig(config);
}

int ConfigStore::closeAppsWaitSeconds() const
{
    bool ok = false;
    const int value = loadConfig().value(QStringLiteral("CLOSE_APPS_WAIT_SECONDS")).toString().toInt(&ok);
    if (!ok) {
        return 5;
    }
    if (value < 0) {
        return 0;
    }
    if (value > 60) {
        return 60;
    }
    return value;
}

bool ConfigStore::setCloseAppsWaitSeconds(int seconds) const
{
    if (seconds < 0) {
        seconds = 0;
    }
    if (seconds > 60) {
        seconds = 60;
    }
    QVariantMap config = loadConfig();
    config.insert(QStringLiteral("CLOSE_APPS_WAIT_SECONDS"), QString::number(seconds));
    return saveConfig(config);
}

QStringList ConfigStore::appsToClose() const
{
    const QString raw = loadConfig().value(QStringLiteral("APPS_TO_CLOSE")).toString();
    if (raw.isEmpty()) {
        return {};
    }
    return raw.split(',', Qt::SkipEmptyParts);
}

bool ConfigStore::setAppsToClose(const QStringList &apps) const
{
    QVariantMap config = loadConfig();
    config.insert(QStringLiteral("APPS_TO_CLOSE"), apps.join(','));
    return saveConfig(config);
}
