#include "configstore.h"

#include <QDBusConnection>
#include <QDBusInterface>
#include <QDBusPendingCall>
#include <QDBusPendingReply>
#include <QDir>
#include <QFile>
#include <QSettings>
#include <QTextStream>

namespace {
QString normalizeValue(const QString &raw)
{
    QString value = raw.trimmed();
    if (value.size() >= 2 && value.startsWith('\'') && value.endsWith('\'')) {
        value = value.mid(1, value.length() - 2);
    }
    return value;
}
}

ConfigStore::ConfigStore(QObject *parent)
    : QObject(parent)
{
}

QString ConfigStore::configFilePath()
{
    const QString base = qEnvironmentVariableIsSet("XDG_CONFIG_HOME")
        ? qEnvironmentVariable("XDG_CONFIG_HOME")
        : QDir::homePath() + QStringLiteral("/.config");
    return base + QStringLiteral("/open-couch-engine/config.env");
}


QVariantMap ConfigStore::loadConfig() const
{
    QVariantMap config;
    QFile file(configFilePath());
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return config;
    }

    QTextStream stream(&file);
    while (!stream.atEnd()) {
        const QString line = stream.readLine().trimmed();
        if (line.isEmpty() || line.startsWith('#')) {
            continue;
        }

        const int eq = line.indexOf('=');
        if (eq <= 0) {
            continue;
        }

        const QString key = line.left(eq).trimmed();
        QString value = normalizeValue(line.mid(eq + 1));
        if (!key.isEmpty()) {
            config.insert(key, value);
        }
    }
    return config;
}

bool ConfigStore::saveConfig(const QVariantMap &config) const
{
    const QString path = configFilePath();
    QDir().mkpath(QFileInfo(path).absolutePath());

    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
        return false;
    }

    QTextStream stream(&file);
    stream << "# Generated by the Open Couch app - do not edit manually while the app is running\n";
    for (auto it = config.constBegin(); it != config.constEnd(); ++it) {
        stream << it.key() << "='" << it.value().toString().replace("'", "'\\''") << "'\n";
    }
    return true;
}

bool ConfigStore::autostartEnabled() const
{
    return QSettings().value(QStringLiteral("autostartEnabled"), false).toBool();
}

bool ConfigStore::setAutostart(bool enabled) const
{
    return requestBackgroundPortal(enabled);
}

bool ConfigStore::requestBackgroundPortal(bool enabled) const
{
    QDBusInterface portal (
        QStringLiteral("org.freedesktop.portal.Desktop"),
        QStringLiteral("/org/freedesktop/portal/desktop"),
        QStringLiteral("org.freedesktop.portal.Background"),
        QDBusConnection::sessionBus()
    );

    if (!portal.isValid()) {
        return false;
    }

    QVariantMap options;
    options[QStringLiteral("reason")] =
        QStringLiteral("Used to monitor Steam and automatically switch displays.");
    options[QStringLiteral("autostart")] = enabled;
    options[QStringLiteral("commandLine")] = QStringList{QStringLiteral("opencouch")};
    options[QStringLiteral("dbus-activatable")] = false;

    QDBusPendingCall pending = portal.asyncCall(
        QStringLiteral("RequestBackground"),
        QStringLiteral(""),
        options
    );

    // Store the intended preference immediately; portal dialog is shown asunchronously
    QSettings().setValue(QStringLiteral("autostartEnabled"), enabled);

    QDBusPendingReply<QDBusObjectPath> reply(pending);
    reply.waitForFinished();
    return !reply.isError();
}

bool ConfigStore::backgroundOnClose() const
{
    return QSettings().value(QStringLiteral("backgroundOnClose"), true).toBool();
}

bool ConfigStore::setBackgroundOnClose(bool enabled) const
{
    QSettings settings;
    settings.setValue(QStringLiteral("backgroundOnClose"), enabled);
    return true;
}

bool ConfigStore::onboardingSeen() const
{
    QSettings settings;
    return settings.value(QStringLiteral("onboardingSeen"), false).toBool();
}

void ConfigStore::setOnboardingSeen(bool seen) const
{
    QSettings settings;
    settings.setValue(QStringLiteral("onboardingSeen"), seen);
}
